version: '2'
services:  

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=clouddatabase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root@123
    ports:
      - 3307:3306  

  myapp-main:
    image: backend
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root@123
      - DATABASE_NAME=clouddatabase
      - DATABASE_PORT=3306