pipeline {
    agent any

    stages {
        stage('Checkout SCM') {
            steps {
                git branch: 'DevOps', url: 'https://github.com/muhilkennedy/generic_webapplication.git' 
            }
        }
        stage('Build') {
            steps {
                    dir('services/tenantmanagement') {
                        sh 'mvn clean install'
                    }
                  }
        }
        stage('Build Docker Image') {
            steps {
                    dir('services/tenantmanagement') {
                        sh 'ansible-playbook image.yml'
                    }
                  }
        }
    }
}