pipeline {
    agent any
    stages {
        stage('Checkout SCM') {
            steps { 
                checkout scmGit(branches: [[name: '*/DevOps']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/muhilkennedy/generic_webapplication.git']])
            }
        }
        stage('Maven Build'){
            steps{
                dir('/var/lib/jenkins/workspace/Docker-Image/services/tenant-management') {
                      sh 'mvn clean install'
              }
            }
        }
        stage('Remove Old version Docker Image'){
            steps{
                dir('/var/lib/jenkins/workspace/Docker-Image/services/tenant-management') {
                      sh 'docker rmi $(docker images -a -q)'
              }
            }
        }         
        stage('Docker Image Build'){
            steps{
                dir('/var/lib/jenkins/workspace/Docker-Image/services/tenant-management') {
                      sh 'docker build -t tenent .'
              }
            }
        }        
    }
}