pipeline {
    agent any
    stages {
        stage('Build image') {
            steps { 
                checkout scmGit(branches: [[name: '*/DevOps']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/muhilkennedy/generic_webapplication.git']])
            }
        }
    }
}