/* BASE USER TABLES */
CREATE TABLE IF NOT EXISTS employee (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, active BOOL DEFAULT TRUE, fname varchar(50) NOT NULL, lname varchar(50) NOT NULL, mobile varchar(15) NOT NULL, emailid varchar(50) NOT NULL, password varchar(255), profilepic varchar(100), timecreated bigint, timeupdated bigint, modifiedby varchar(64), version bigint DEFAULT 0, createdby varchar(64), locale varchar(12) default 'en_US', timezone varchar(64), lastactive bigint, lastlogin bigint, designation varchar(64), reportsto varchar(64), CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid), UNIQUE KEY `con_emp_email` (`tenantid`,`emailid`), UNIQUE KEY `con_emp_mobile` (`tenantid`,`mobile`));
CREATE TABLE IF NOT EXISTS employeeinfo (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, active BOOL DEFAULT TRUE, dob varchar(32), gender varchar(12), proofurl varchar(255), timecreated bigint, timeupdated bigint, modifiedby varchar(64), createdby varchar(64), version bigint DEFAULT 0, CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));
CREATE TABLE IF NOT EXISTS employeeactivity (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, active BOOL DEFAULT TRUE, timecreated bigint, timeupdated bigint, modifiedby varchar(64), createdby varchar(64), version bigint DEFAULT 0, login datetime, logout datetime, CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));
CREATE TABLE IF NOT EXISTS employeepreference (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, active BOOL DEFAULT TRUE, timecreated bigint, timeupdated bigint, modifiedby varchar(64), createdby varchar(64), version bigint DEFAULT 0, mode varchar(32), newuser BOOL DEFAULT TRUE, CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));

CREATE TABLE IF NOT EXISTS customer (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, active BOOL DEFAULT TRUE, fname varchar(50) NOT NULL, lname varchar(50), mobile varchar(15), emailid varchar(50), password varchar(255), origin varchar(10), profilepic varchar(100), lastactive bigint, lastlogin bigint, timecreated bigint, timeupdated bigint, modifiedby varchar(64), createdby varchar(64), version bigint DEFAULT 0, locale varchar(12) default 'en_US', timezone varchar(64), CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid), UNIQUE KEY `con_cus_email` (`tenantid`,`emailid`), UNIQUE KEY `con_cus_mobile` (`tenantid`,`mobile`));

/* Default data*/

INSERT INTO EMPLOYEE(rootid, tenantid, active, fname, lname, emailid, mobile, password, locale, timezone, timecreated, timeupdated) values ("1:USER", "tenant1", true, "support", "admin", "superuser", "0000000000", "$2a$05$MhdU7apzW37pNyu77/1xt.ICQdYmri/q4e.606JZQFFGaYNDyiUXG", "en_US", "IST", 0, 0);
INSERT INTO EMPLOYEE(rootid, tenantid, active, fname, lname, emailid, mobile, password, locale, timezone, timecreated, timeupdated) values ("ADMINTENANT:USER", "ADMINTENANT", true, "customersupport", "admin", "superuser", "0000000000", "$2a$05$FnCFD1U3J5Nfmsv9MeYWp.FS.Sf1moUOFpuqu0WtjzYHKb0mGIcfC", "en_US", "IST", 0, 0);

