/* BASE TRANSACTION TABLES */
CREATE TABLE IF NOT EXISTS tenant (rootid varchar(64) NOT NULL PRIMARY KEY, tenantuniquename varchar(64) NOT NULL UNIQUE, tenantname varchar(100) NOT NULL, active BOOL DEFAULT TRUE, purgetenant BOOL DEFAULT FALSE, timecreated bigint, timeupdated bigint, modifiedby varchar(64));
CREATE TABLE IF NOT EXISTS tenantdetails (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL UNIQUE, tenantcontact varchar(15), tenantemail varchar(100), tenantbusinessemail varchar(100), businessemailpassword varchar(100), tenantstreet varchar(200), tenantcity varchar(100), tenantpin varchar(10), tenantlogo MEDIUMBLOB, tenantfacebook varchar(100), tenanttwitter varchar(100), tenantinsta varchar(100), gstin varchar(50), fssai varchar(50), tagline varchar(256), gmaplocation varchar(1000), timecreated bigint, timeupdated bigint, active BOOL DEFAULT TRUE, modifiedby varchar(64), CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));
CREATE TABLE IF NOT EXISTS tenantorigins (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, origin varchar(256), timecreated bigint, timeupdated bigint, active BOOL DEFAULT TRUE, modifiedby varchar(64), CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));

CREATE TABLE IF NOT EXISTS featuretoggle (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, featurename varchar(30) NOT NULL UNIQUE, timecreated bigint, timeupdated bigint, active BOOL DEFAULT TRUE, modifiedby varchar(64), CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));
CREATE TABLE IF NOT EXISTS scheduledtaskaudit (rootid varchar(64) NOT NULL PRIMARY KEY, tenantid varchar(64) NOT NULL, taskname varchar(75) NOT NULL, starttime DATETIME DEFAULT CURRENT_TIMESTAMP, endtime DATETIME , status varchar(25), failureinfo varchar(1000), timecreated bigint, timeupdated bigint, active BOOL DEFAULT TRUE, modifiedby varchar(64), CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));

CREATE TABLE IF NOT EXISTS sequencenumber (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid varchar(64) NOT NULL, classname varchar(100), nextvalue bigint, incrementvalue bigint, timecreated bigint, timeupdated bigint, active BOOL DEFAULT TRUE, modifiedby varchar(64), CONSTRAINT FOREIGN KEY(tenantid) REFERENCES tenant(rootid));


INSERT INTO tenant (rootid, tenantuniquename, tenantname, active, timeupdated, timecreated) values (1, "devTenant", "DevTenant", true, 0, 0);
INSERT INTO tenant (rootid, tenantuniquename, tenantname, active, timeupdated, timecreated) values (2, "prodTenant", "prodTenant", true, 1996, 1996);